FROM jenkins/inbound-agent:latest-bookworm-jdk17
USER root
RUN apt-get update && apt-get install -y git 

# Update the package repository and install OpenJDK 11
RUN apt-get update && apt-get install -y default-jdk
RUN cd /tmp
RUN curl -o apache-maven-3.9.5-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
RUN tar xzf apache-maven-3.9.5-bin.tar.gz -C /opt/
RUN cd /opt/
RUN ln -s apache-maven-3.9.5 maven
RUN echo -e "export M2_HOME=/opt/apache-maven-3.9.5\nexport PATH=\${M2_HOME}/bin:\${PATH}" | tee /etc/profile.d/maven.sh
RUN /bin/bash -c "source /etc/profile.d/maven.sh"
RUN /bin/bash -c "mvn -version"
# Switch back to jenkins user
USER jenkins

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]