apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  completions: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: ["--dockerfile=./Dockerfile-jenkins-agent-inbound-make",
               "--context=git://github.com/mrlicmi/jenkins-agents-custom.git",
               "--destination=milic/jenkins-agent:make",
              ]
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
        - name: kaniko-secret
          secret:
            secretName: reg-credentials
            items:
              - key: .dockerconfigjson
                path: config.json
